services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/todo
    ports:
      - 8080:8080
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/todo
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/todo
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - redis