# Generated by Django 4.2.16 on 2024-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
